
import { Industry } from './types';

export const translations: any = {
    en: {
        practice: "Interview Coach",
        welcomeBack: "Master your interview skills with AI. Select a role to begin.",
        generatingQuestions: "AI is crafting your interview...",
        couldNotLoadQuestions: "Could not generate questions. Please try again.",
        stopRecording: "Stop Recording",
        recordingComplete: "Recording Complete",
        transcribing: "Transcribing...",
        transcriptionFailed: "Transcription failed. Please try again.",
        answerTooShort: "Answer is too short. Please elaborate.",
        analyzingResponse: "AI is analyzing your response...",
        tapToRecord: "Tap microphone to start answering...",
        transcribe: "Transcribe",
        getNewQuestion: "Skip Question",
        getFeedback: "Submit Answer",
        feedbackTitle: "Performance Analysis",
        overallScore: "Overall Score",
        englishClarity: "Communication Clarity",
        confidence: "Confidence Level",
        roleUnderstanding: "Role Knowledge",
        yourStrengths: "What You Did Well",
        yourNextFocus: "Areas for Improvement",
        speechAnalytics: "Speech Analytics",
        speakingPace: "Speaking Pace",
        fillerWords: "Filler Words Detected",
        modelAnswer: "Suggested Answer",
        modelAnswerTab: "Model Answer",
        copy: "Copy",
        copied: "Copied!",
        finishSession: "End Session",
        tryAgain: "Retry Question",
        nextQuestion: "Next Question",
        overview: "Overview",
        analysis: "Detailed Analysis",
        noApiKey: "API Key Missing",
        
        // Industries & Rounds
        cabinCrew: "Cabin Crew",
        cabinCrewDesc: "Prepare for top international and domestic airlines.",
        airportStaff: "Airport Ground Staff",
        airportStaffDesc: "Master roles like CSA, Ramp, and Security.",
        hotelJob: "Hotel Management",
        hotelJobDesc: "Specialized prep for 5-Star Hotel Departments.",
        
        introRound: "Introduction & HR",
        groomingRound: "Grooming & Standards",
        serviceRound: "Service Scenarios",
        emergencyRound: "Emergency & Safety",
        csaRound: "Customer Service (CSA)",
        securityRound: "Aviation Security (AvSec)",
        rampRound: "Ramp Operations",
        cargoRound: "Cargo & Logistics",
        frontOfficeRound: "Front Office",
        fnbRound: "Food & Beverage",
        housekeepingRound: "Housekeeping",
        kitchenRound: "Culinary (Kitchen)"
    },
    hi: {
        practice: "इंटरव्यू कोच",
        welcomeBack: "AI के साथ अपने साक्षात्कार कौशल में महारत हासिल करें। शुरू करने के लिए एक भूमिका चुनें।",
        generatingQuestions: "AI आपका इंटरव्यू तैयार कर रहा है...",
        couldNotLoadQuestions: "प्रश्न उत्पन्न नहीं हो सके। कृपया पुन: प्रयास करें।",
        stopRecording: "रिकॉर्डिंग रोकें",
        recordingComplete: "रिकॉर्डिंग पूरी हुई",
        transcribing: "लिप्यांतरण (Transcribing) हो रहा है...",
        transcriptionFailed: "लिप्यांतरण विफल रहा।",
        answerTooShort: "उत्तर बहुत छोटा है। कृपया विस्तार से बताएं।",
        analyzingResponse: "AI आपके उत्तर का विश्लेषण कर रहा है...",
        tapToRecord: "उत्तर देने के लिए माइक टैप करें...",
        transcribe: "टेक्स्ट में बदलें",
        getNewQuestion: "प्रश्न छोड़ें",
        getFeedback: "उत्तर जमा करें",
        feedbackTitle: "प्रदर्शन विश्लेषण",
        overallScore: "कुल स्कोर",
        englishClarity: "संचार स्पष्टता",
        confidence: "आत्मविश्वास",
        roleUnderstanding: "भूमिका का ज्ञान",
        yourStrengths: "आपकी ताकत",
        yourNextFocus: "सुधार के क्षेत्र",
        speechAnalytics: "भाषण विश्लेषण",
        speakingPace: "बोलने की गति",
        fillerWords: "अनावश्यक शब्द (Fillers)",
        modelAnswer: "सुझाया गया उत्तर",
        modelAnswerTab: "आदर्श उत्तर",
        copy: "कॉपी करें",
        copied: "कॉपी किया गया!",
        finishSession: "सत्र समाप्त करें",
        tryAgain: "पुनः प्रयास करें",
        nextQuestion: "अगला प्रश्न",
        overview: "अवलोकन",
        analysis: "विस्तृत विश्लेषण",
        noApiKey: "API कुंजी गायब है",

        // Industries & Rounds
        cabinCrew: "केबिन क्रू (Cabin Crew)",
        cabinCrewDesc: "शीर्ष अंतरराष्ट्रीय और घरेलू एयरलाइनों के लिए तैयारी करें।",
        airportStaff: "एयरपोर्ट ग्राउंड स्टाफ",
        airportStaffDesc: "सीएसए, रैंप और सुरक्षा जैसी भूमिकाओं में महारत हासिल करें।",
        hotelJob: "होटल मैनेजमेंट",
        hotelJobDesc: "5-सितारा होटल विभागों के लिए विशेष तैयारी।",

        introRound: "परिचय और एचआर (HR)",
        groomingRound: "ग्रूमिंग और मानक",
        serviceRound: "सेवा परिदृश्य (Service)",
        emergencyRound: "आपातकालीन और सुरक्षा",
        csaRound: "ग्राहक सेवा (CSA)",
        securityRound: "विमानन सुरक्षा (AvSec)",
        rampRound: "रैंप ऑपरेशन्स",
        cargoRound: "कार्गो और लॉजिस्टिक्स",
        frontOfficeRound: "फ्रंट ऑफिस",
        fnbRound: "खाद्य और पेय (F&B)",
        housekeepingRound: "हाउसकीपिंग",
        kitchenRound: "पाक कला (Kitchen)"
    },
    gu: {
        practice: "ઇન્ટરવ્યુ કોચ",
        welcomeBack: "AI સાથે તમારી ઇન્ટરવ્યુ કુશળતા સુધારો. શરૂ કરવા માટે રોલ પસંદ કરો.",
        generatingQuestions: "AI તમારા પ્રશ્નો તૈયાર કરી રહ્યું છે...",
        couldNotLoadQuestions: "પ્રશ્નો લોડ થઈ શક્યા નથી. કૃપા કરીને ફરી પ્રયાસ કરો.",
        stopRecording: "રેકોર્ડિંગ બંધ કરો",
        recordingComplete: "રેકોર્ડિંગ પૂર્ણ",
        transcribing: "લખાઈ રહ્યું છે...",
        transcriptionFailed: "ટ્રાન્સક્રિપ્શન નિષ્ફળ ગયું.",
        answerTooShort: "જવાબ ખૂબ ટૂંકો છે. કૃપા કરીને વિગતવાર જણાવો.",
        analyzingResponse: "AI તમારા જવાબનું વિશ્લેષણ કરી રહ્યું છે...",
        tapToRecord: "જવાબ આપવા માટે માઇક ટેપ કરો...",
        transcribe: "લખવું",
        getNewQuestion: "પ્રશ્ન છોડો",
        getFeedback: "જવાબ સબમિટ કરો",
        feedbackTitle: "પ્રદર્શન વિશ્લેષણ",
        overallScore: "કુલ સ્કોર",
        englishClarity: "વાતચીતની સ્પષ્ટતા",
        confidence: "આત્મવિશ્વાસ",
        roleUnderstanding: "રોલ નોલેજ",
        yourStrengths: "તમારી શક્તિઓ",
        yourNextFocus: "સુધારણા માટેના ક્ષેત્રો",
        speechAnalytics: "સ્પીચ એનાલિટિક્સ",
        speakingPace: "બોલવાની ગતિ",
        fillerWords: "વધારાના શબ્દો",
        modelAnswer: "સૂચવેલ જવાબ",
        modelAnswerTab: "આદર્શ જવાબ",
        copy: "કોપી",
        copied: "કોપી થયું!",
        finishSession: "સત્ર સમાપ્ત કરો",
        tryAgain: "ફરી પ્રયાસ કરો",
        nextQuestion: "આગળનો પ્રશ્ન",
        overview: "ઝાંખી",
        analysis: "વિગતવાર વિશ્લેષણ",
        noApiKey: "API કી ખૂટે છે",

        // Industries & Rounds
        cabinCrew: "કેબિન ક્રૂ (Cabin Crew)",
        cabinCrewDesc: "શ્રેષ્ઠ આંતરરાષ્ટ્રીય અને સ્થાનિક એરલાઇન્સ માટે તૈયારી કરો.",
        airportStaff: "એરપોર્ટ ગ્રાઉન્ડ સ્ટાફ",
        airportStaffDesc: "CSA, રેમ્પ અને સિક્યુરિટી જેવા રોલ્સ માટે તૈયારી.",
        hotelJob: "હોટેલ મેનેજમેન્ટ",
        hotelJobDesc: "5-સ્ટાર હોટેલ વિભાગો માટે વિશેષ તૈયારી.",

        introRound: "પરિચય અને HR",
        groomingRound: "ગ્રૂમિંગ અને સ્ટાન્ડર્ડ્સ",
        serviceRound: "સર્વિસ સિનારિયો",
        emergencyRound: "ઇમરજન્સી અને સેફ્ટી",
        csaRound: "ગ્રાહક સેવા (CSA)",
        securityRound: "એવિએશન સિક્યુરિટી (AvSec)",
        rampRound: "રેમ્પ ઓપરેશન્સ",
        cargoRound: "કાર્ગો અને લોજિસ્ટિક્સ",
        frontOfficeRound: "ફ્રન્ટ ઓફિસ",
        fnbRound: "ફૂડ અને બેવરેજ (F&B)",
        housekeepingRound: "હાઉસકીપિંગ",
        kitchenRound: "ક્યુલિનરી (રસોડું)"
    }
};

export const industryData = (t: (key: string) => string): Industry[] => [
    {
        id: 'cabinCrew',
        title: t('cabinCrew'),
        description: t('cabinCrewDesc'),
        rounds: [
            { id: 'intro', title: t('introRound') },
            { id: 'grooming', title: t('groomingRound') },
            { id: 'service', title: t('serviceRound') },
            { id: 'emergency', title: t('emergencyRound') }
        ]
    },
    {
        id: 'airportStaff',
        title: t('airportStaff'),
        description: t('airportStaffDesc'),
        rounds: [
            { id: 'csa', title: t('csaRound') },
            { id: 'security', title: t('securityRound') },
            { id: 'ramp', title: t('rampRound') },
            { id: 'cargo', title: t('cargoRound') }
        ]
    },
    {
        id: 'hotelJob',
        title: t('hotelJob'),
        description: t('hotelJobDesc'),
        rounds: [
            { id: 'frontOffice', title: t('frontOfficeRound') },
            { id: 'fnb', title: t('fnbRound') },
            { id: 'housekeeping', title: t('housekeepingRound') },
            { id: 'kitchen', title: t('kitchenRound') }
        ]
    }
];
